### PR TITLE
Use UIWebView to authenticate instead of diverting to MobileSafari

### PR DESCRIPTION
**Pull request by DaGaMs**
This is a merge of Evernote API 1.21 with Matt McGlincy's branch.

### CODE REVIEW

**Comment by sethhitch** [comment]
Thanks, we merged Matt's pull request and also pulled in the cancellation fix that you added.

**Comment by DaGaMs** [comment]
Are you at WWDC? Want to have a coffee?

Sent from my iPad

**Comment by sethhitch** [comment]
I'm not, unfortunately, I'm down in our Redwood City office. How long are you in town for?

**Comment by DaGaMs** [comment]
Unfortunately we're heading out to Palo Alto later today. My flight back to Europe is on Wednesday afternoon, I might make it back to SF earlier in the day.

Best,

Ben

## 

Benjamin Schuster-Böckler
ben@mekentosj.com

Follow me on Twitter: 
http://twitter.com/dagams

Visit us at:
http://www.mekentosj.com

**Pull request closed without merging**
